// Code generated by OpenAPI-Generator

part of 'models.dart';

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: avoid_init_to_null, prefer_expression_function_bodies
// ignore_for_file: omit_local_variable_types, prefer_collection_literals,
// ignore_for_file: curly_braces_in_flow_control_structures, avoid_types_on_closure_parameters,
// ignore_for_file: unnecessary_const, constant_identifier_names, unnecessary_new

class CardBrand {
  /// The underlying value of this enum member.
  final String value;

  const CardBrand._internal(this.value);

  static const CardBrand visa_ = const CardBrand._internal("Visa");
  static const CardBrand masterCard_ = const CardBrand._internal("MasterCard");
  static const CardBrand jCB_ = const CardBrand._internal("JCB");
  static const CardBrand americanExpress_ =
      const CardBrand._internal("American Express");
  static const CardBrand dinersClub_ = const CardBrand._internal("Diners Club");
  static const CardBrand discover_ = const CardBrand._internal("Discover");

  static CardBrand fromJson(String value) {
    return new CardBrandTypeTransformer().decode(value);
  }

  static List<CardBrand> listFromJson(List<dynamic> json) {
    return json.map((value) => CardBrand.fromJson(value as String)).toList();
  }
}

class CardBrandTypeTransformer {
  dynamic encode(CardBrand data) {
    return data.value;
  }

  CardBrand decode(dynamic data) {
    switch (data) {
      case "Visa":
        return CardBrand.visa_;
      case "MasterCard":
        return CardBrand.masterCard_;
      case "JCB":
        return CardBrand.jCB_;
      case "American Express":
        return CardBrand.americanExpress_;
      case "Diners Club":
        return CardBrand.dinersClub_;
      case "Discover":
        return CardBrand.discover_;
      default:
        throw ('Unknown enum value to decode: $data');
    }
  }
}
