// Code generated by OpenAPI-Generator

part of 'models.dart';

class Token {
  /* tok_で始まる一意なオブジェクトを示す文字列 */
  late String id;

  late Card card;
  /* このトークン作成時のタイムスタンプ */
  late int created;
  /* 本番環境かどうか */
  late bool livemode;
  /* \\\"token\\\"の固定文字列 */
  late String object;
  /* このトークンが使用済みかどうか */
  late bool used;
  Token();

  @override
  String toString() {
    return 'Token[id=$id, card=$card, created=$created, livemode=$livemode, object=$object, used=$used, ]';
  }

  Token.fromJson(Map<dynamic, dynamic> json) {
    id = json['id'];
    card = Card.fromJson(json['card']);
    created = json['created'];
    livemode = json['livemode'];
    object = json['object'];
    used = json['used'];
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> json = {};
    json['id'] = id;
    json['card'] = card;
    json['created'] = created;
    json['livemode'] = livemode;
    json['object'] = object;
    json['used'] = used;
    return json;
  }

  static List<Token> listFromJson(List<dynamic> json) {
    return json.map((value) => Token.fromJson(value)).toList();
  }

  static Map<String, Token> mapFromJson(Map<String, dynamic> json) {
    var map = Map<String, Token>();
    if (json.isNotEmpty) {
      json.forEach(
          (String key, dynamic value) => map[key] = Token.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of Token-objects as value to a dart map
  static Map<String, List<Token>> mapListFromJson(Map<String, dynamic> json) {
    var map = Map<String, List<Token>>();
    if (json.isNotEmpty) {
      json.forEach((String key, dynamic value) {
        map[key] = Token.listFromJson(value);
      });
    }
    return map;
  }
}

// ignore_for_file: avoid_init_to_null, prefer_expression_function_bodies, omit_local_variable_types, prefer_collection_literals, curly_braces_in_flow_control_structures, avoid_types_on_closure_parameters, unnecessary_const, constant_identifier_names, unnecessary_new
