// Code generated by OpenAPI-Generator

part of 'models.dart';

class Token {
  /* tok_で始まる一意なオブジェクトを示す文字列 */
  String id = null;

  Card card = null;
  /* このトークン作成時のタイムスタンプ */
  int created = null;
  /* 本番環境かどうか */
  bool livemode = null;
  /* \\\"token\\\"の固定文字列 */
  String object = null;
  /* このトークンが使用済みかどうか */
  bool used = null;
  Token();

  @override
  String toString() {
    return 'Token[id=$id, card=$card, created=$created, livemode=$livemode, object=$object, used=$used, ]';
  }

  Token.fromJson(Map<dynamic, dynamic> json) {
    if (json == null) return;
    id = json['id'];
    card = (json['card'] == null) ? null : Card.fromJson(json['card']);
    created = json['created'];
    livemode = json['livemode'];
    object = json['object'];
    used = json['used'];
  }

  Map<String, dynamic> toJson() {
    Map<String, dynamic> json = {};
    if (id != null) json['id'] = id;
    if (card != null) json['card'] = card;
    if (created != null) json['created'] = created;
    if (livemode != null) json['livemode'] = livemode;
    if (object != null) json['object'] = object;
    if (used != null) json['used'] = used;
    return json;
  }

  static List<Token> listFromJson(List<dynamic> json) {
    return json == null
        ? List<Token>()
        : json.map((value) => Token.fromJson(value)).toList();
  }

  static Map<String, Token> mapFromJson(Map<String, dynamic> json) {
    var map = Map<String, Token>();
    if (json != null && json.isNotEmpty) {
      json.forEach(
          (String key, dynamic value) => map[key] = Token.fromJson(value));
    }
    return map;
  }

  // maps a json object with a list of Token-objects as value to a dart map
  static Map<String, List<Token>> mapListFromJson(Map<String, dynamic> json) {
    var map = Map<String, List<Token>>();
    if (json != null && json.isNotEmpty) {
      json.forEach((String key, dynamic value) {
        map[key] = Token.listFromJson(value);
      });
    }
    return map;
  }
}

// ignore_for_file: avoid_init_to_null, prefer_expression_function_bodies, omit_local_variable_types, prefer_collection_literals, curly_braces_in_flow_control_structures, avoid_types_on_closure_parameters, unnecessary_const, constant_identifier_names, unnecessary_new
